variables:
  GIT_USER: gitlab-ci-token
  GIT_PASS: $CI_JOB_TOKEN

stages:
- build

build:
  stage: build
  only:
  - tags
  script:
  - >-
    docker build .
    --push
    --tag $PRIVATE_DOCKER_REPOSITORY/tzdb.dat:$CI_COMMIT_TAG
    --tag $PRIVATE_DOCKER_REPOSITORY/tzdb.dat:latest
