variables:
  GIT_USER: gitlab-ci-token
  GIT_PASS: $CI_JOB_TOKEN

before_script:
- export TAG=$CI_COMMIT_TAG

stages:
- build
- release

build:
  stage: build
  only:
  - tags
  script:
  - docker build -t $PRIVATE_DOCKER_REPOSITORY/tzdb.dat:$TAG . --force-rm $DOCKER_BUILD_OPTS

publish:
  stage: release
  only:
  - tags
  script:
  - docker tag $PRIVATE_DOCKER_REPOSITORY/tzdb.dat:$TAG $PRIVATE_DOCKER_REPOSITORY/tzdb.dat:latest
  - docker push $PRIVATE_DOCKER_REPOSITORY/tzdb.dat:$TAG
  - docker push $PRIVATE_DOCKER_REPOSITORY/tzdb.dat:latest
